[tox]
envlist = py27,py34,py35,py36,py37,py38

[testenv]
changedir=test
commands=discover
deps=-rrequirements_test.txt

[testenv:docs]
basepython=python
deps=-rrequirements_docs.txt
changedir=docs/source
commands=
    sphinx-build -b html -d {envtmpdir}/doctrees .  {envtmpdir}/html
