[tox]
envlist = py27,py36

[testenv]
changedir=test
commands=discover
deps =
    discover
    simplejson
    future

[testenv:docs]
basepython=python
deps=-rrequirements_docs.txt
changedir=docs/source
commands=
    sphinx-build -b html -d {envtmpdir}/doctrees .  {envtmpdir}/html
